### ISSUE TITLE
sub2quanx转换surge链接失败

### ISSUE THREAD

**Issue by aglent** [KOP-XIAO/QuantumultX-Surge-API#1]
https://dove.589669.xyz/sub2quanx?type=surge......
使用机场suge订阅或list 转换到圈x 提示【Internal Server Error】
使用ss订阅链接等转换没有问题
不知问题出在哪里

**Comment by KOP-XIAO** [comment]
确定链接转码没写错么？另外，如果是rix之类的某几家机场，是不支持第三方api的

**Comment by aglent** [comment]
> 确定链接转码没写错么？另外，如果是rix之类的某几家机场，是不支持第三方api的
我试了
二个机场N3和Yoyu  surge list都没有成功 换成SIP002可以的

**Comment by aglent** [comment]
https://dove.589669.xyz/sub2quanx?type=surge&sub=xxx&emoji=2&filter=xxx  sub和filter都用urlencode  语法应该没问题的

**Comment by KOP-XIAO** [comment]
再试试，应该可以了

**Comment by aglent** [comment]
> 
> 
> 再试试，应该可以了

成功了 非常感谢
另外问下 哪些机场不支持这个api？

**Comment by KOP-XIAO** [comment]
除了那些禁止第三方api获取的机场，其它的应该都行。
