### ISSUE TITLE
是否可以自动添加节点类型参数

### ISSUE THREAD

**Issue by tkfanswind** [KOP-XIAO/QuantumultX-Surge-API#11]
类似于T大append_type参数
自动在节点前面加上线路类型
[SS]或者[VMess]

**Comment by KOP-XIAO** [comment]
有 rename 参数让你加啊

**Comment by tkfanswind** [comment]
我的意思是自动判断是什么类型，自动加上[SS]或者[VMess]
用 rename 的话，同一个订阅里可能有两种类型SS或者V2，用名字也区分不开
