### ISSUE TITLE
out只能过滤一个参数

### ISSUE THREAD

**Issue by c1awn** [KOP-XIAO/QuantumultX-Surge-API#14]
比如out=3倍+5倍编码后，只有3倍被过滤

**Comment by KOP-XIAO** [comment]
试了下，没问题哦

**Comment by c1awn** [comment]
> 试了下，没问题哦

![5DA5D338-A5FF-4BC8-B328-865D408CC151](https://user-images.githubusercontent.com/29470764/76481815-6e0fa580-644d-11ea-90fa-e3d9d9251af6.jpeg)
转换订阅是https://dove.589669.xyz/all2quanx?&udp=1&tfo=1&emoji=22&info=1&sub=https://订阅已删减EqY%3Fsub%3D3%26extend%3D1&filter=%E9%A6%99%E6%B8%AF%7C%E6%96%B0%E5%8A%A0%E5%9D%A1%7C%E5%8F%B0%E6%B9%BE%7C%E7%BE%8E%E5%9B%BD%7C%E6%97%A5%E6%9C%AC&out=3%E5%80%8D+5%E5%80%8D+8%E5%80%8D
感谢回复，可以帮忙看看问题出在哪里么

**Comment by KOP-XIAO** [comment]
out=3%E5%80%8D%2B5%E5%80%8D%2B8%E5%80%8D
+号也是需要urlencode的

**Comment by c1awn** [comment]
> out=3%E5%80%8D%2B5%E5%80%8D%2B8%E5%80%8D
> +号也是需要urlencode的

Soga，可以了。有人根据您的api制作的ios捷径，我增加了out过滤，[捷径链接](https://www.icloud.com/shortcuts/e253a99b547d411dafee4fdebfb8d518)
