### ISSUE TITLE
做一个前端吧，直接用域名好多人压根看都看不明白，包括需要的地址的要求

### ISSUE THREAD

**Issue by 1204TMax** [KOP-XIAO/QuantumultX-Surge-API#15]
做一个前端吧，直接用域名好多人压根看都看不明白，包括需要的地址的要求

**Comment by phlinhng** [comment]
有API就能自己做前端了，何必麻煩作者？你看不明白說明這個項目不是讓你看明白的

**Comment by 1204TMax** [comment]
我用词不当好吧，我是建议做一个前端，我寻思这么长还挺美观的文档都写了，前端也就一个input一个按钮的事儿，既然不愿意我也不会说什么，毕竟我并不使用这个项目，所以对我而言并无利害关系可言
