### ISSUE TITLE
mac上的clashX无法使用

### ISSUE THREAD

**Issue by gwhcn** [KOP-XIAO/QuantumultX-Surge-API#21]
希望出一个转clashX规则的，订阅链接支持v2ray的base64格式（例：vmess://xxxxxxx==），自己塔的梯子，没有订阅服务器

**Comment by KOP-XIAO** [comment]
你用gist做一个订阅就好了

**Comment by gwhcn** [comment]
![20201112101038](https://user-images.githubusercontent.com/20394691/98886699-8568cc00-24cf-11eb-901d-4346500dc756.jpg)
clashx使用生成的神机规则报错

**Comment by KOP-XIAO** [comment]
请使用clashx pro

**Comment by gwhcn** [comment]
> 请使用clashx pro

谢谢，可以了，生成的配置第234行报错，需要下载下来删除这一行
