### ISSUE TITLE
HotKids 策略组託管參數配置

### ISSUE THREAD

**Issue by deepfish** [KOP-XIAO/QuantumultX-Surge-API#22]
我這邊使用了HotKids 的策略組託管訂閱，但是託管訂閱不能設置遠程訪問（局域網通過我的surge聯網），所以想問問可以增加一些設置嗎？託管的時候可以自定義某一些選項。

**Comment by KOP-XIAO** [comment]
比如哪些选项呢？

**Comment by deepfish** [comment]
> 比如哪些选项呢？

例如以下常用選項：
1.是否支持遠程服務（給局域網其它設備使用）；
2.是否開啟 IPv6 支持；
3.錯誤頁可以默認顯示；
4.當前默認使用系統 DNS，建議加上一些公共的 DNS。
PS：測試的 URL 直接填 bing，會不會不太合適？

**Comment by KOP-XIAO** [comment]
这些部分，你都可以通过自己添加额外模块来实现。
配置文件开头也都写了。
例如：
https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Module/Profile.sgmodule

**Comment by deepfish** [comment]
> 这些部分，你都可以通过自己添加额外模块来实现。
> 配置文件开头也都写了。
> 例如：
> https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Module/Profile.sgmodule

好的，謝謝，我嘗試一下。
