### ISSUE TITLE
clashx pro 托管配置下载报错

### ISSUE THREAD

**Issue by wangbo-ops** [KOP-XIAO/QuantumultX-Surge-API#24]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/71998512/113266870-53ce9100-9308-11eb-8fcc-0141fe726b26.png">
下载文件后发现是265行的缩进tab不是space造成的，麻烦大佬能否修复一下，这样后续托管的配置更新时就不会报错了。

**Comment by wangbo-ops** [comment]
输出类型选择的是神机规则原版
<img width="657" alt="image" src="https://user-images.githubusercontent.com/71998512/113267278-bf186300-9308-11eb-8cee-16f6085003ca.png">

**Comment by KOP-XIAO** [comment]
具体是哪一行，能截图么？
我的265可能跟你的265不是同一行，而且我这边也没报错提示

**Comment by wangbo-ops** [comment]
> 具体是哪一行，能截图么？
> 我的265可能跟你的265不是同一行，而且我这边也没报错提示

<img width="594" alt="image" src="https://user-images.githubusercontent.com/71998512/113273617-6ac4b180-930f-11eb-8736-0318e620985c.png">

**Comment by KOP-XIAO** [comment]
修了 应该可以了

**Comment by wangbo-ops** [comment]
> 修了 应该可以了

又报新的错误了大佬😂
<img width="372" alt="image" src="https://user-images.githubusercontent.com/71998512/113274932-ce031380-9310-11eb-8fc8-9505772df9b8.png">

**Comment by KOP-XIAO** [comment]
我这边能正常用呀😯
@ShawnKOP_bot
你把完整链接发给这个反馈bot

**Comment by KOP-XIAO** [comment]
telegram bot ：https://t.me/ShawnKOP_bot

**Comment by wangbo-ops** [comment]
> telegram bot ：https://t.me/ShawnKOP_bot

发了，大佬

**Comment by wangbo-ops** [comment]
大佬，下载rules好像有点问题，我在bot上跟你反馈了
![image](https://user-images.githubusercontent.com/71998512/113389681-0400d000-93c3-11eb-9162-6ee4fc1dbe75.png)
