### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by iam3ddy** [KOP-XIAO/QuantumultX-Surge-API#3]
Hi,

Could you guide me how to the emoji?

i have added emoji=2 and also tried adding &rename=🇨🇳 台湾@🇹🇼 台湾
encoded as &rename=%F0%9F%87%A8%F0%9F%87%B3%20%E5%8F%B0%E6%B9%BE%40%F0%9F%87%B9%F0%9F%87%BC%20%E5%8F%B0%E6%B9%BE

thanks in advance

**Comment by KOP-XIAO** [comment]
So what is the problem?
if you want to get 🇹🇼, just use the parameter &emoji=1

**Comment by iam3ddy** [comment]
thanks. emoji=1 works!
