### ISSUE TITLE
emoji问题

### ISSUE THREAD

**Issue by BaileyZyp** [KOP-XIAO/QuantumultX-Surge-API#4]
我把两个订阅链接拼接起来，一个订阅链接没有emoji另外个有emoji
然后添加了emoji=2的参数，没有emoji的订阅正常，有emoji的订阅会丢失节点参数只剩下节点名称 如图
![9733FDB8-3A62-40E9-8921-7282A5DD0AAE](https://user-images.githubusercontent.com/16634459/68102701-d1715000-ff0e-11e9-86b6-b482fc670ebb.png)

**Comment by KOP-XIAO** [comment]
具体是哪个 api？

**Comment by BaileyZyp** [comment]
> 具体是哪个 api？

Surge
QX没试过

**Comment by KOP-XIAO** [comment]
应该好了

**Comment by BaileyZyp** [comment]
> 应该好了

还有个问题
https://dove.589669.xyz/Mix2Surge?type=surge&tfo=1&udp=1&emoji=2&sub=Surge2的托管订阅
转换完成后还是surge2的节点格式 没有tfo和udp的参数 emoji参数正常

**Comment by KOP-XIAO** [comment]
surge转 surge 的话就是这样的设计的，原链接内容什么样，转换后就什么样，也不会修改 udp/tfo参数。

**Comment by ghost** [comment]
为何🇷🇺俄罗斯的订阅显示新加坡国旗？🇸🇬
![Uploading 4C6B023A-99E1-4F42-A36E-40A7EB556838.jpeg…]()

**Comment by RainyMoment** [comment]
![4C6B023A-99E1-4F42-A36E-40A7EB556838](https://user-images.githubusercontent.com/59493737/73118290-17c5d080-3f8d-11ea-8623-3321d11f886a.jpeg)

**Comment by KOP-XIAO** [comment]
> 为何🇷🇺俄罗斯的订阅显示新加坡国旗？🇸🇬

不该吧？emoji是根据节点名字添加的
