### ISSUE TITLE
节点过滤

### ISSUE THREAD

**Issue by BaileyZyp** [KOP-XIAO/QuantumultX-Surge-API#5]
现在的过滤功能是匹配保留节点
能否增加一个匹配删除节点
比如说我不需要回国节点和游戏节点
或者订阅里面有官网地址一些乱七八糟的东西

**Comment by KOP-XIAO** [comment]
既然是正则过滤，那就是匹配保留/匹配删除都能实现，自己去看看正则的写法

**Comment by BaileyZyp** [comment]
您的意思是把需要保留的节点关键字全部写进正则过滤里吗？
比如我用QX但我只想删除一两个节点信息其他全部保留
如果有很多地区节点那我就要写很长的正则参数以后增加了其他地区节点我将会不知道 如下图
![F0AD7088-998A-424E-AFAF-1DA73121BAB5](https://user-images.githubusercontent.com/16634459/68104303-87d83380-ff15-11e9-8367-b72dfbf3fff7.png)

**Comment by KOP-XIAO** [comment]
> 您的意思是把需要保留的节点关键字全部写进正则过滤里吗？
> 比如我用 QX 但我只想删除一两个节点信息其他全部保留
> 如果有很多地区节点那我就要写很长的正则参数以后增加了其他地区节点我将会不知道 如下图
> ![F0AD7088-998A-424E-AFAF-1DA73121BAB5](https://user-images.githubusercontent.com/16634459/68104303-87d83380-ff15-11e9-8367-b72dfbf3fff7.png)

正则是可以直接匹配 "非"的，具体自己看正则教程啊

**Comment by BaileyZyp** [comment]
> > 您的意思是把需要保留的节点关键字全部写进正则过滤里吗？
> > 比如我用 QX 但我只想删除一两个节点信息其他全部保留
> > 如果有很多地区节点那我就要写很长的正则参数以后增加了其他地区节点我将会不知道 如下图
> > ![F0AD7088-998A-424E-AFAF-1DA73121BAB5](https://user-images.githubusercontent.com/16634459/68104303-87d83380-ff15-11e9-8367-b72dfbf3fff7.png)
> 
> 正则是可以直接匹配 "非"的，具体自己看正则教程啊

好的，谢谢

**Comment by BaileyZyp** [comment]
> > 您的意思是把需要保留的节点关键字全部写进正则过滤里吗？
> > 比如我用 QX 但我只想删除一两个节点信息其他全部保留
> > 如果有很多地区节点那我就要写很长的正则参数以后增加了其他地区节点我将会不知道 如下图
> > ![F0AD7088-998A-424E-AFAF-1DA73121BAB5](https://user-images.githubusercontent.com/16634459/68104303-87d83380-ff15-11e9-8367-b72dfbf3fff7.png)
> 
> 正则是可以直接匹配 "非"的，具体自己看正则教程啊

我试了还是会保留不知道我写的正则对不对
以下是我的正则
[^不保留的节点名称]*

**Comment by KOP-XIAO** [comment]
^ 是表示匹配开头而已，哪来的匹配非。。
比如你不想要名字以  加拿大或者法国开头的 节点，那就是 (?!加拿大|法国)
正则问题自行去看正则教程

**Comment by BaileyZyp** [comment]
> ^ 是表示匹配开头而已，哪来的匹配非。。
> 比如你不想要名字以 加拿大或者法国开头的 节点，那就是 (?!加拿大|法国)
> 正则问题自行去看正则教程

![97005481-B2FF-466D-A91A-BFB1743D8EED](https://user-images.githubusercontent.com/16634459/68177570-b1e82f00-ffc3-11e9-9d9b-a02a38cd2ab0.png)
你给的教程是这么说的

**Comment by BaileyZyp** [comment]
> (?!加拿大|法国)

您所说的这个正则我试了也不行

**Comment by KOP-XIAO** [comment]
不会吧。。
tg私聊我。 @XIAO_KOP
