### ISSUE TITLE
订阅合并问题和排序问题

### ISSUE THREAD

**Issue by tkfanswind** [KOP-XIAO/QuantumultX-Surge-API#6]
1.现在好像不同类型的订阅不能合并。比如第一个订阅是SS类型，第二个订阅是V2类型。想合并到一起放在一个组里，多个订阅不同类型时候那个type没办法填写，实现一一对应多个类型的订阅地址。
2.现在排序和添加国旗同时开启的时候，默认是先加国旗再排序，如果想实现先排序再添加国旗。不知道怎么配置和实现？现在这个顺序调整不了。谢谢

**Comment by KOP-XIAO** [comment]
1.类型问题，可以用新的 all2quanx 跟 all2surge ，可以随意混搭类型，无需type参数；
2.排序问题，把emoji当作排序元素也算合理吧。如果再细分，还显得太麻烦了，暂时就不改了

**Comment by tkfanswind** [comment]
all2surge all2quanx还没发布吧？暂时没看到

如果能控制排序和emoji的执行顺序就能解决。不知道容易不。麻烦就算了


Shawn <notifications@github.com>于2020年1月3日 周五21:52写道：

**Comment by KOP-XIAO** [comment]
你直接把sub2quanx(Mix2Surge)改成 all2quanx(all2surge)就行了。
