### ISSUE TITLE
回国过滤

### ISSUE THREAD

**Issue by tkfanswind** [KOP-XIAO/QuantumultX-Surge-API#7]
🏴‍☠️  
filter 使用 "回国" 时候会匹配上上面那个字符（好像是个海盗旗）
导致错误

**Comment by KOP-XIAO** [comment]
没看懂

**Comment by tkfanswind** [comment]
回国
过滤节点的时候。海盗国旗那行会过滤出来。只有海盗国旗。没有节点信息。因为多了这一行。所以会报错



Shawn <notifications@github.com>于2020年1月9日 周四16:59写道：

**Comment by KOP-XIAO** [comment]
![image](https://user-images.githubusercontent.com/45581750/72055844-7b51cc00-3306-11ea-822c-a2f746e34a5a.png)
没发现有什么问题。
另外，这种问题，如果不想发订阅链接，没法帮你测试，也就没必要发issue了

**Comment by tkfanswind** [comment]
我一会整理一下思路，写清楚发上来

Shawn <notifications@github.com>于2020年1月9日 周四17:37写道：

**Comment by tkfanswind** [comment]
好像已经好了。奇怪。感谢
