### ISSUE TITLE
可否添加流量信息，节点更新信息提示

### ISSUE THREAD

**Issue by tkfanswind** [KOP-XIAO/QuantumultX-Surge-API#8]
原生的订阅地址QuantumultX支持显示流量信息和节点更新信息提示。
但是通过大大的API之后，这些信息就不显示了。据说是http header实现的
不知可否支持这一功能？挺不错的

如果两个订阅地址合并是否也能支持显示这些信息？

**Comment by KOP-XIAO** [comment]
用新的那个 all2quanx 的api，有个 &info=1 参数，可以保留header里面的“用量信息”。
但多个订阅合并的话，只会保留其中的一个信息，因为quanx只支持一个。

**Comment by tkfanswind** [comment]
多个订阅合并的话,保留的是哪个订阅地址的信息？最前面还是最后面的？

header中的用量信息&节点更新信息都会保留吗？

**Comment by KOP-XIAO** [comment]
保留最后一个header中有用量信息的。
header中不存在什么“节点更新信息”，你应该是误解了什么。

**Comment by tkfanswind** [comment]
Quantumult X更新订阅的时候，节点有变化的时候会有提示信息。这个跟套不套API无关？

**Comment by KOP-XIAO** [comment]
这显然是quanx本地直接检测节点变化然后通知的啊。
你觉得会有机场主还把节点的增减记录到header里？

**Comment by tkfanswind** [comment]
好的。明白了。感谢
