### ISSUE TITLE
surge list转换问题

### ISSUE THREAD

**Issue by Fsick** [KOP-XIAO/QuantumultX-Surge-API#9]
大佬，使用您的api转换quanx正常 表示机场支持api以及我的正则表达没有问题，但是改为surge的时候，现实解析远程资源失败。
  surge版本为4.1 build1464  通过手机直接访问得到的是 surge-node.list.html quanx为txt文件  是不是我的步骤出错了？

**Comment by KOP-XIAO** [comment]
去私聊 bot 发链接给我看看。

 surge 提示解析失败，那应该是转换后的格式不符合它规范
